services:
  - type: web
    name: api
    plan: standard
    region: ohio
    dockerfilePath: docker/api/Dockerfile.amd64
    envVars:
      - key: CONNECTIONSTRINGS__DEFAULTCONNECTION
        value: ${DATABASE_CONNECTION}
      - key: AUTH0__DOMAIN
        value: ${AUTH0_DOMAIN}
      - key: AUTH0__AUDIENCE
        value: ${AUTH0_AUDIENCE}
      - key: ALLOWED_ORIGINS
        value: '*'
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: THESPORTSDB__APIKEY
        value: ${THESPORTSDB_API_KEY}
      - key: THESPORTSDB__URL
        value: ${THESPORTSDB_URL}
      - key: ALLOWEDEMAILS__ENTRIES
        value: boondockgeek@gmail.com,paul@kelly.ky
      - key: PORT
        value: 80

  - type: web
    name: web
    plan: standard
    region: ohio
    dockerfilePath: docker/web/Dockerfile.amd64
    envVars:
      - key: APIBASEURL
        value: ${API_BASE_URL}
      - key: AUTH0__DOMAIN
        value: ${AUTH0_DOMAIN}
      - key: AUTH0__CLIENTID
        value: ${AUTH0_CLIENT_ID}
      - key: AUTH0__CLIENTSECRET
        value: ${AUTH0_CLIENT_SECRET}
      - key: AUTH0__AUDIENCE
        value: ${AUTH0_AUDIENCE}
      - key: PORT
        value: 80