services:
  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile.amd64
    restart: unless-stopped
    ports:
      - "${API_PORT}:80"
    environment:
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=${DATABASE_CONNECTION}
      - AUTH0__DOMAIN=${AUTH0_DOMAIN}
      - AUTH0__AUDIENCE=${AUTH0_AUDIENCE}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - THESPORTSDB__APIKEY=${THESPORTSDB_API_KEY}
      - THESPORTSDB__URL=${THESPORTSDB_URL}
      - ALLOWEDEMAILS=${ALLOWED_EMAILS}
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true

  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile.amd64
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - API_BASE_URL=http://api:80
      - AUTH0__DOMAIN=${AUTH0_DOMAIN}
      - AUTH0__CLIENTID=${AUTH0_CLIENT_ID}
      - AUTH0__CLIENTSECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0__AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0__CALLBACKPATH=/callback
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    depends_on:
      - api
