version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/api/Dockerfile.amd64
    restart: unless-stopped
    ports:
      - "${API_PORT}:80"
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - Auth0__Domain=${AUTH0_DOMAIN}
      - Auth0__Audience=${AUTH0_AUDIENCE}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile.amd64
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - ApiBaseUrl=${API_BASE_URL}
      - Auth0__Domain=${AUTH0_DOMAIN}
      - Auth0__ClientId=${AUTH0_CLIENT_ID}
    depends_on:
      - api
