// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Picus.Api.Data;

#nullable disable

namespace Picus.Api.Migrations
{
    [DbContext(typeof(PicusDbContext))]
    [Migration("20241226151553_RemoveEspnId")]
    partial class RemoveEspnId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Picus.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ESPNGameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlayoffs")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PickDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Picus.Api.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("Picus.Api.Models.Pick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SelectedTeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Picks");
                });

            modelBuilder.Entity("Picus.Api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Conference")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalTeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TertiaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "BAL",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/bal.png",
                            City = "Baltimore",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "33",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
                            Name = "Ravens",
                            PrimaryColor = "#241773",
                            SecondaryColor = "#000000",
                            TertiaryColor = "#9E7C0C"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "CIN",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/cin.png",
                            City = "Cincinnati",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "4",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
                            Name = "Bengals",
                            PrimaryColor = "#FB4F14",
                            SecondaryColor = "#000000",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "CLE",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/cle.png",
                            City = "Cleveland",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "5",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
                            Name = "Browns",
                            PrimaryColor = "#311D00",
                            SecondaryColor = "#FF3C00",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "PIT",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/pit.png",
                            City = "Pittsburgh",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "23",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
                            Name = "Steelers",
                            PrimaryColor = "#FFB612",
                            SecondaryColor = "#101820",
                            TertiaryColor = "#A5ACAF"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "HOU",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/hou.png",
                            City = "Houston",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "34",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
                            Name = "Texans",
                            PrimaryColor = "#03202F",
                            SecondaryColor = "#A71930",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "IND",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/ind.png",
                            City = "Indianapolis",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "11",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
                            Name = "Colts",
                            PrimaryColor = "#002C5F",
                            SecondaryColor = "#A2AAAD",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "JAX",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/jax.png",
                            City = "Jacksonville",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "30",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
                            Name = "Jaguars",
                            PrimaryColor = "#006778",
                            SecondaryColor = "#9F792C",
                            TertiaryColor = "#000000"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "TEN",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/ten.png",
                            City = "Tennessee",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "10",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
                            Name = "Titans",
                            PrimaryColor = "#0C2340",
                            SecondaryColor = "#4B92DB",
                            TertiaryColor = "#C8102E"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "BUF",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/buf.png",
                            City = "Buffalo",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "2",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
                            Name = "Bills",
                            PrimaryColor = "#00338D",
                            SecondaryColor = "#C60C30",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "MIA",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/mia.png",
                            City = "Miami",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "15",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
                            Name = "Dolphins",
                            PrimaryColor = "#008E97",
                            SecondaryColor = "#FC4C02",
                            TertiaryColor = "#005778"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "NE",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/ne.png",
                            City = "New England",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "17",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
                            Name = "Patriots",
                            PrimaryColor = "#002244",
                            SecondaryColor = "#C60C30",
                            TertiaryColor = "#B0B7BC"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "NYJ",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/nyj.png",
                            City = "New York",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "20",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
                            Name = "Jets",
                            PrimaryColor = "#125740",
                            SecondaryColor = "#000000",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "DEN",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/den.png",
                            City = "Denver",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "7",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
                            Name = "Broncos",
                            PrimaryColor = "#FB4F14",
                            SecondaryColor = "#002244",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "KC",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/kc.png",
                            City = "Kansas City",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "12",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
                            Name = "Chiefs",
                            PrimaryColor = "#E31837",
                            SecondaryColor = "#FFB81C",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "LV",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/lv.png",
                            City = "Las Vegas",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "13",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
                            Name = "Raiders",
                            PrimaryColor = "#000000",
                            SecondaryColor = "#A5ACAF",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "LAC",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/lac.png",
                            City = "Los Angeles",
                            Conference = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "24",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
                            Name = "Chargers",
                            PrimaryColor = "#0080C6",
                            SecondaryColor = "#FFC20E",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "CHI",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/chi.png",
                            City = "Chicago",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "3",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
                            Name = "Bears",
                            PrimaryColor = "#0B162A",
                            SecondaryColor = "#C83803",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "DET",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/det.png",
                            City = "Detroit",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "8",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
                            Name = "Lions",
                            PrimaryColor = "#0076B6",
                            SecondaryColor = "#B0B7BC",
                            TertiaryColor = "#000000"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "GB",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/gb.png",
                            City = "Green Bay",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "9",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
                            Name = "Packers",
                            PrimaryColor = "#203731",
                            SecondaryColor = "#FFB612",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "MIN",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/min.png",
                            City = "Minnesota",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 0,
                            ExternalTeamId = "16",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
                            Name = "Vikings",
                            PrimaryColor = "#4F2683",
                            SecondaryColor = "#FFC62F",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "ATL",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/atl.png",
                            City = "Atlanta",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "1",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
                            Name = "Falcons",
                            PrimaryColor = "#A71930",
                            SecondaryColor = "#000000",
                            TertiaryColor = "#A5ACAF"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "CAR",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/car.png",
                            City = "Carolina",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "29",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
                            Name = "Panthers",
                            PrimaryColor = "#0085CA",
                            SecondaryColor = "#101820",
                            TertiaryColor = "#BFC0BF"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "NO",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/no.png",
                            City = "New Orleans",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "18",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
                            Name = "Saints",
                            PrimaryColor = "#D3BC8D",
                            SecondaryColor = "#101820",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "TB",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/tb.png",
                            City = "Tampa Bay",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 1,
                            ExternalTeamId = "27",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
                            Name = "Buccaneers",
                            PrimaryColor = "#D50A0A",
                            SecondaryColor = "#FF7900",
                            TertiaryColor = "#B1BABF"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "DAL",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/dal.png",
                            City = "Dallas",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "6",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
                            Name = "Cowboys",
                            PrimaryColor = "#003594",
                            SecondaryColor = "#041E42",
                            TertiaryColor = "#869397"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "NYG",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/nyg.png",
                            City = "New York",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "19",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
                            Name = "Giants",
                            PrimaryColor = "#0B2265",
                            SecondaryColor = "#A71930",
                            TertiaryColor = "#A5ACAF"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "PHI",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/phi.png",
                            City = "Philadelphia",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "21",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
                            Name = "Eagles",
                            PrimaryColor = "#004C54",
                            SecondaryColor = "#A5ACAF",
                            TertiaryColor = "#ACC0C6"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "WSH",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/wsh.png",
                            City = "Washington",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 2,
                            ExternalTeamId = "28",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
                            Name = "Commanders",
                            PrimaryColor = "#5A1414",
                            SecondaryColor = "#FFB612",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "ARI",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/ari.png",
                            City = "Arizona",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "22",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
                            Name = "Cardinals",
                            PrimaryColor = "#97233F",
                            SecondaryColor = "#000000",
                            TertiaryColor = "#FFB612"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "LAR",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/lar.png",
                            City = "Los Angeles",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "14",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
                            Name = "Rams",
                            PrimaryColor = "#003594",
                            SecondaryColor = "#FFA300",
                            TertiaryColor = "#FF8200"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "SF",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/sf.png",
                            City = "San Francisco",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "25",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
                            Name = "49ers",
                            PrimaryColor = "#AA0000",
                            SecondaryColor = "#B3995D",
                            TertiaryColor = "#FFFFFF"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "SEA",
                            BannerUrl = "https://a.espncdn.com/i/teamlogos/nfl/500-dark/sea.png",
                            City = "Seattle",
                            Conference = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Division = 3,
                            ExternalTeamId = "26",
                            IconUrl = "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
                            Name = "Seahawks",
                            PrimaryColor = "#002244",
                            SecondaryColor = "#69BE28",
                            TertiaryColor = "#A5ACB0"
                        });
                });

            modelBuilder.Entity("Picus.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.HasIndex("LeagueId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Picus.Api.Models.Game", b =>
                {
                    b.HasOne("Picus.Api.Models.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Picus.Api.Models.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Picus.Api.Models.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("Picus.Api.Models.League", b =>
                {
                    b.HasOne("Picus.Api.Models.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("Picus.Api.Models.Pick", b =>
                {
                    b.HasOne("Picus.Api.Models.Game", "Game")
                        .WithMany("Picks")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Picus.Api.Models.Team", "SelectedTeam")
                        .WithMany("Picks")
                        .HasForeignKey("SelectedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Picus.Api.Models.User", "User")
                        .WithMany("Picks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("SelectedTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Picus.Api.Models.User", b =>
                {
                    b.HasOne("Picus.Api.Models.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Picus.Api.Models.Game", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Picus.Api.Models.League", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Picus.Api.Models.Team", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Picus.Api.Models.User", b =>
                {
                    b.Navigation("Picks");
                });
#pragma warning restore 612, 618
        }
    }
}
