name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'PicusPicks.Web/**'
      - 'PicusPicks.Web.Tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'PicusPicks.Web/**'
      - 'PicusPicks.Web.Tests/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Publish
      run: dotnet publish PicusPicks.Web/PicusPicks.Web.csproj -c Release -o publish
    
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "publish/wwwroot" # The location of your Blazor WebAssembly output
        skip_app_build: true # Since we've already built it